<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>WaitForIt</PackageId>
        <Version>0.0.2</Version>
        <Authors>Martin Blomster, Johan Granlund, Jonas Lundblad</Authors>
        <Company>Thruput</Company>
        <Description>A fluent, time-bound, assertion-based waiting library for .NET</Description>
        <PackageTags>testing;await;assertion;wait</PackageTags>
        <RepositoryUrl>https://github.com/thruput-io/WaitForIt</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/your-org/waitforit</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <RootNamespace>WaitForIt</RootNamespace>
    </PropertyGroup>

</Project>
